// Generated by CoffeeScript 1.6.2
/*
The Encoder module

@todo write Tokeniser class
@todo write Type_Converter class
@todo write Expression_Tree_Generator class
*/


(function() {
  CALCULATINAIRE.Encoder = {};

}).call(this);
